name: whats_news
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    equatable: ^2.0.5
    json_annotation: ^4.8.1
    copy_with_extension: ^5.0.4
    dio: ^5.3.2
    flutter_hooks: ^0.20.1
    hooks_riverpod: ^2.4.0
    flutter_dotenv: ^5.1.0
    url_launcher: ^6.1.14
    hive: ^4.0.0-dev.2
    isar_flutter_libs: ^4.0.0-dev.13
    path_provider: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    json_serializable: ^6.7.1
    build_runner: ^2.4.6
    copy_with_extension_gen: ^5.0.4

flutter:
    uses-material-design: true
    assets:
        - .env
